### ISSUE TITLE
Redis Message Bus Implementation

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/wg-data#27]
- [ ] Review output from FC-0008 (https://github.com/openedx/data-wg/issues/22), identify any blockers

- [ ] Fix or document issues, or cancel this whole epic if it is too risky

- [ ] Redis message bus Tutor plugin

**Comment by bmtcril** [comment]
This work is happening in FC-0008 https://openedx.atlassian.net/wiki/spaces/COMM/pages/3612934199/FC-0008+-+Redis+Streams+Event+Bus so I'm going to close this ticket out
